Amber MMPBSA added for the protein-protein docking

diff --git a/Vini b/Vini
--- a/Vini
+++ b/Vini
@@ -130,19 +130,30 @@ cat COPYRIGHT
 read -e -p "Enter your SLURM account provided by admin. Press enter to accept " -i "r2022r03-224-users" slurm_account
 echo $slurm_account > $WORKDIR/slurm_account
 
-if [ -e $WORKDIR/test_compute_nodes ]
+partition=`cat active_partition`
+walltime=6   #max time is 6 minutes
+
+if [ -e $WORKDIR/nodetest ]
 then
-    birth=`stat $WORKDIR/test_compute_nodes | grep Birth`
-    echo "Testing of computing nodes has already been done on $birth. If there have been any changes in the meantime, the procedure should be repeated."
+    birth=`stat $WORKDIR/nodetest | grep Birth`
+    echo "Testing of computing nodes has already been done on $birth. If there have been any changes in the meantime, the procedure should be repeated. Warning: May last up to 1h to finish."
 
     read -e -p "Do you want to repeat the procedure? (y/n). Press enter to accept the default: " -i "n" yesno
     if [ $yesno == y ]
     then
-        sh $vini_dir/test_compute_nodes
+        timeout 10s sh $vini_dir/nodetest $partition $walltime
+        success=`echo $?`
+        if [ $success -eq 124 ] ; then
+           echo "Test aborted, cancelling jobs..." ; scancel -u $USER
+        fi
     fi
 else
-    echo "A cluster health check will now be performed."
-    sh $vini_dir/test_compute_nodes
+    echo "Nodetest will now be performed."
+    timeout 10s sh $vini_dir/nodetest $partition $walltime
+        success=`echo $?`
+        if [ $success -eq 124 ] ; then
+           echo "Test aborted, cancelling jobs..." ; scancel -u $USER
+        fi
 fi
 
 
